package org.tohu.examples.loyalty.loyalty_complex_app;

import java.util.Calendar;
import org.tohu.Group;
import org.tohu.InvalidAnswer;
import org.tohu.MultipleChoiceQuestion;
import org.tohu.MultipleChoiceQuestion.PossibleAnswer;
import org.tohu.Note;
import org.tohu.Question;
import org.tohu.Answer;
import org.tohu.Questionnaire;
import org.tohu.support.TohuDataItemObject;

import org.tohu.examples.loyalty.*;

rule "JointOtherLoyaltyDetailsPage"
dialect "mvel"
no-loop
when
	pe1 : MultipleChoiceQuestion(id == "applicationType" , answer == "2");
then
	Group aGroup = new Group("JointOtherLoyaltyDetailsPage");
	aGroup.setLabel("Please specify the other loyalty programs for the applicant.");
	aGroup.setItems({
		"JointNameSummaryItems",
		"JointLoyaltyProgramItems"});
	insertLogical(aGroup);
end

rule "JointNameSummaryItems"
dialect "mvel"
no-loop
when
	$group : Group (id == "JointOtherLoyaltyDetailsPage");
then
	Group aGroup = new Group("JointNameSummaryItems");
	aGroup.setLabel("7");
	aGroup.setItems({
		"givenNamesJoint",
		"surnameJoint"});
	aGroup.setPresentationStyles({
		"readonly",
		"row"});
	insertLogical(aGroup);
end

rule "JointLoyaltyProgramItems"
dialect "mvel"
no-loop
when
	$group : Group (id == "JointOtherLoyaltyDetailsPage");
then
	Group aGroup = new Group("JointLoyaltyProgramItems");
	aGroup.setItems({
		"budgetAirwaysJoint",
		"onlineFoodJoint",
		"mochaCoffeeJoint"});
	insertLogical(aGroup);
end

rule "budgetAirwaysJoint"
dialect "mvel"
no-loop
when
	$group : Group (id == "JointLoyaltyProgramItems");
then
	Question aQuestion = new Question("budgetAirwaysJoint");
	aQuestion.setAnswerType(Question.TYPE_BOOLEAN);
	aQuestion.setAnswer(false);
	aQuestion.setPreLabel("Budget Airways?");
	aQuestion.setPresentationStyles({"yesNoButtons"});
	insertLogical(aQuestion);
end

rule "onlineFoodJoint"
dialect "mvel"
no-loop
when
	$group : Group (id == "JointLoyaltyProgramItems");
then
	Question aQuestion = new Question("onlineFoodJoint");
	aQuestion.setAnswerType(Question.TYPE_BOOLEAN);
	aQuestion.setAnswer(false);
	aQuestion.setPreLabel("Online Food?");
	aQuestion.setPresentationStyles({"yesNoButtons"});
	insertLogical(aQuestion);
end

rule "mochaCoffeeJoint"
dialect "mvel"
no-loop
when
	$group : Group (id == "JointLoyaltyProgramItems");
then
	Question aQuestion = new Question("mochaCoffeeJoint");
	aQuestion.setAnswerType(Question.TYPE_BOOLEAN);
	aQuestion.setAnswer(false);
	aQuestion.setPreLabel("Mocha Coffee?");
	aQuestion.setPresentationStyles({"yesNoButtons"});
	insertLogical(aQuestion);
end

