package org.tohu.examples.loyalty;

import org.tohu.Group;
import org.tohu.InvalidAnswer;
import org.tohu.MultipleChoiceQuestion;
import org.tohu.MultipleChoiceQuestion.PossibleAnswer;
import org.tohu.Note;
import org.tohu.Question;
import org.tohu.Answer;
import org.tohu.Questionnaire;
import org.tohu.support.TohuDataItemObject;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Arrays;

rule "LoyaltyCard"
dialect "mvel"
then
	Questionnaire questionnaire = new Questionnaire("LoyaltyCard");
	questionnaire.setLabel("Solnet Loyalty Card Signup");
	questionnaire.setCompletionAction("extract.pdf");
	questionnaire.setItems({"ContactDetailsPage"});
	questionnaire.setActiveItem("ContactDetailsPage");
	questionnaire.setEnableActionValidation(false);
	insertLogical(questionnaire);
end

declare ListEntryFact
	id : String @key
end

